### ISSUE TITLE
refactor: Test Refactor

### ISSUE THREAD

**Issue by nicoloboo02** [ISPP-07/frontend-cyc#42]
## Feature Description
Due to the big change that the application has undergone in the last few days, a refactoring of all the tests has to be done to check that everything works correctly.
## Motivation
This is necessary so that the application is consistent and the vast majority of errors are detected as early as possible.
## Acceptance Criteria
- [ ] [Criteria 1: All tests run]
- [ ] [Criteria 2: New tests have been added]
- [ ] [Criteria 3: Test coverage has increased]

**Comment by AntonioRodriguezRuiz** [comment]
what repository is this for?
