### ISSUE TITLE
feat: Filter and search

### ISSUE THREAD

**Issue by alejandromd** [ISPP-07/frontend-cyc#43]
## Feature Description
To make the search bar of both beneficiaries and interventions work.

## Motivation
This change is necessary because at certain times when NGOs need to search and filter them.

## Acceptance Criteria
- [ ] Criteria 1: To make the search bar of families work
- [ ] Criteria 2: To make the search bar of deliveries work
- [ ] Criteria 3: To make the search bar of food work

**Comment by sebasruii** [comment]
This feature was initially planned for S2, but after a meeting last week we've decided to move it to S3.
